import type { Metadata } from "next";
// import localFont from "next/font/local";
import {DM_Sans } from 'next/font/google'
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";

const font=DM_Sans({subsets:['latin']})

export const metadata: Metadata = {
  title: "My SAAS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
     <html lang="en" suppressHydrationWarning>
     <body
        className={`${font?.className} antialiased`}
        >
      <ThemeProvider           
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
   
        {children}
      </ThemeProvider>
      </body>

    </html>
  );
}
